broadinstitute/dig-loam-stream

src/main/scala/loamstream/apps/AppWiring.scala
src/main/scala/loamstream/conf/DrmConfig.scala
src/main/scala/loamstream/drm/uger/UgerDefaults.scala
src/main/scala/loamstream/drm/uger/UgerPathBuilder.scala
src/main/scala/loamstream/drm/uger/UgerScriptBuilderParams.scala
src/main/scala/loamstream/model/execute/CompositeChunkRunner.scala
src/main/scala/loamstream/model/execute/Settings.scala
src/test/scala/loamstream/apps/AppWiringTest.scala
src/test/scala/loamstream/conf/UgerConfigTest.scala
src/test/scala/loamstream/drm/DrmChunkRunnerTest.scala
src/test/scala/loamstream/drm/DrmJobWrapperTest.scala
src/test/scala/loamstream/drm/DrmTaskArrayTest.scala
src/test/scala/loamstream/drm/ScriptBuilderTest.scala
src/test/scala/loamstream/drm/uger/UgerPathBuilderTest.scala
src/test/scala/loamstream/drm/uger/UgerScriptBuilderParamsTest.scala
src/test/scala/loamstream/model/execute/DrmSettingsTest.scala

- Allows configuring Conda bin path and the Conda environment to activate in scripts submitted to Uger.
- Added `extraPathDir` and `condaEnvName` to `loamstream.uger` section of `loamstream.conf`:
```
loamstream {
...
uger {
...
extraPathDir = "/humgen/diabetes/users/dig/miniconda2/bin"
condaEnvName = "loamstream_v1.0"
}
...
}
```
- `UgerScriptBuilderParams` and `UgerPathBuilder` now take params.
Note: The integration tests passed.

Allow configuring Conda Env activated by Uger scripts

---

src/main/scala/loamstream/apps/AppWiring.scala
src/main/scala/loamstream/conf/DrmConfig.scala
src/main/scala/loamstream/drm/uger/UgerDefaults.scala
src/main/scala/loamstream/drm/uger/UgerNativeSpecBuilder.scala
src/main/scala/loamstream/drm/uger/UgerScriptBuilderParams.scala
src/main/scala/loamstream/model/execute/Settings.scala
src/test/scala/loamstream/apps/AppWiringTest.scala
src/test/scala/loamstream/conf/UgerConfigTest.scala
src/test/scala/loamstream/drm/uger/UgerNativeSpecBuilderTest.scala
src/test/scala/loamstream/drm/uger/UgerScriptBuilderParamsTest.scala

Previously, the "native spec", a set of flags analagous to `qsub` params, used when submitting Uger jobs was hard-coded.  This PR makes it configurable in `loamstream.conf`.
- `loamstream.conf` now allows an optional string, `loamstream.uger.staticJobSubmissionParams`.  If this is not present, the previously hard-coded value - `-cwd -shell y -b n` is used.
- If it's present, its value forms the beginning of the native spec that's passed to Uger, not the whole thing.  As before, the rest is built dynamically from job-specific settings (number of cores, memory, max runtime, etc).
NOTE: The Uger integration tests passed.  This should be merged *after* #310 .

Allow Configuring Uger native spec in loamstream.conf

---

src/main/scala/loamstream/compiler/LoamCompiler.scala
src/main/scala/loamstream/model/execute/RxExecuter.scala
src/main/scala/loamstream/model/jobs/JobRun.scala
src/test/scala/loamstream/model/execute/RxExecuterTest.scala
src/test/scala/loamstream/model/jobs/JobRunTest.scala

- Fix a bug where in complex pipelines, duplicates of the same job would be run concurrently.  This happened non-deterministically, but required there to be multiple paths from a root job to another job in the graph.  There was/is a race where the same job can become runnable via multiple paths.  This fix just de-dupes runnable jobs after the streams of runnable jobs reached via all paths are multiplexed.
It's simple, but doesn't address the root cause, which is treating the graph of jobs as a forest of job trees.  The comments also reflect that a previous call to `.distinct` in the same place led to spiraling memory use before.  This version actually uses much _less_ memory according to my profiler when wiring up and running the BioMe pipeline (the worst-case scenario in terms of number …

De-dupe JobRuns in RxExecuter based on their jobs' ids and run counts

---

src/main/scala/loamstream/drm/uger/UgerNativeSpecBuilder.scala
src/test/scala/loamstream/drm/uger/UgerNativeSpecBuilderTest.scala

- This asks for gigabytes instead of gibibytes.
The unit and integration tests passed when run by Jenkins.

Use G instead of g when specifying memory requests to Uger.

---

src/main/scala/loamstream/apps/AppWiring.scala
src/main/scala/loamstream/conf/DrmConfig.scala
src/main/scala/loamstream/drm/uger/QacctAccountingClient.scala
src/main/scala/loamstream/drm/uger/UgerDefaults.scala
src/test/scala/loamstream/conf/UgerConfigTest.scala
src/test/scala/loamstream/drm/uger/MockQacctAccountingClient.scala
src/test/scala/loamstream/drm/uger/QacctAccountingClientTest.scala
src/test/scala/loamstream/drm/uger/UgerResourceUsageExtractorTest.scala

- Retry `qacct` if it fails, up to `loamstream.uger.maxQacctRetries` (from `loamstream.conf`) times.
- Default is to retry `qacct` at most 9 times, or in other words, run `qacct` a maximum of 10 times.
- Wait longer and longer in between subsequent failures, starting at 0.5s and doubling each time, up to 30s.

Retry Qacct a configurable number of times if it fails

---

src/main/scala/loamstream/googlecloud/GoogleCloudChunkRunner.scala
src/main/scala/loamstream/model/execute/AsyncLocalChunkRunner.scala
src/main/scala/loamstream/model/execute/CompositeChunkRunner.scala
src/main/scala/loamstream/model/execute/RxExecuter.scala
src/main/scala/loamstream/util/Observables.scala
src/test/scala/loamstream/googlecloud/GoogleCloudChunkRunnerTest.scala
src/test/scala/loamstream/model/execute/CompositeChunkRunnerTest.scala
src/test/scala/loamstream/model/execute/ExecutionResumptionTest.scala
src/test/scala/loamstream/util/ObservablesTest.scala

Previously, LS ran jobs in chunks, and waited for all the jobs in the chunk to finish before running any jobs that follow on from any of the chunk members.  This means that for a chunk of N jobs, where N - 1 finish quickly, and 1 finishes slowly, the successors of the fast jobs wouldn't run until the slow job finished.  That produced correct results, but meant jobs potentially waited to run for longer than they needed to.
Jenkins-run unit tests passed; the integration tests are ongoing.  @rmkoesterer should also chime in to confirm that this works.

Don't wait for all the jobs in a chunk to finish before running successors of any chunk members

---

src/main/scala/loamstream/model/execute/RxExecuter.scala
src/main/scala/loamstream/model/jobs/JobNode.scala
src/main/scala/loamstream/model/jobs/JobStatus.scala
src/test/scala/loamstream/model/execute/RxExecuterTest.scala
src/test/scala/loamstream/model/jobs/JobStatusTest.scala

This is a minor change that's independent of the other open PRs.  It doesn't change how pipelines run, but it does make for nicer reporting at the end of runs by distinguishing between all the jobs that LS chose not to run and those that ran and then died.

Mark jobs that are cancelled due to missing inputs at execution-time as CouldNotRun instead of FailedPermanently

---

src/it/resources/hail-at-google/loamstream.conf
src/it/scala/loamstream/googlecloud/HailAtGoogleTest.scala
src/main/scala/loamstream/compiler/LoamPredef.scala
src/main/scala/loamstream/db/slick/OutputRow.scala
src/main/scala/loamstream/model/execute/DbBackedJobFilter.scala
src/main/scala/loamstream/model/jobs/DataHandle.scala
src/main/scala/loamstream/model/jobs/StoreRecord.scala
src/test/scala/loamstream/compiler/LoamPredefTest.scala
src/test/scala/loamstream/db/slick/ProvidesSlickLoamDao.scala
src/test/scala/loamstream/model/execute/DbBackedJobFilterTest.scala
src/test/scala/loamstream/model/jobs/DataHandleTest.scala
src/test/scala/loamstream/model/jobs/StoreRecordTest.scala

- Make `DataHandle.{Path,GcsUri}Handle.hash` lazily evaluated
- Make `StoreRecord.{hash,hashType}` lazily evaluated
- Baked-in Google cluster defaults no longer trump values from `loamstream.conf` when using `google { ... }` blocks.
Previously, file hashes were calculated up front for most job outputs, whether or not they were considered. (Ie, if the decision to skip a job or not was made based on file mod time, without even considering hashes, then the hashes still were computed.)  This was a problem for large pipelines operating on large files, since hashing big files is slow.  For example, this PR allows resuming such a pipeline in ~30 minutes, down from ~5.5+ hours.
This PR makes hash computation lazy and ensures the results are cached.  This fixes `--disable-hashing` which didn't …

Respect --disable-hashing, hash files only when needed and cache the results

---

src/main/scala/loamstream/apps/AppWiring.scala
src/main/scala/loamstream/apps/LoamRunner.scala
src/main/scala/loamstream/compiler/LoamEngine.scala
src/main/scala/loamstream/drm/AccountingCommandInvoker.scala
src/main/scala/loamstream/drm/JobMonitor.scala
src/main/scala/loamstream/drm/lsf/BacctAccountingClient.scala
src/main/scala/loamstream/drm/lsf/BacctInvoker.scala
src/main/scala/loamstream/model/execute/Executer.scala
src/main/scala/loamstream/model/execute/RxExecuter.scala
src/main/scala/loamstream/model/jobs/Execution.scala
src/main/scala/loamstream/model/jobs/JobOracle.scala
src/main/scala/loamstream/util/Observables.scala
src/test/scala/loamstream/ExecutionResumptionEndToEndTest.scala
src/test/scala/loamstream/drm/JobMonitorTest.scala
src/test/scala/loamstream/drm/lsf/BacctAccountingClientTest.scala
src/test/scala/loamstream/drm/lsf/BacctInvokerTest.scala
src/test/scala/loamstream/model/execute/ExecutionResumptionTest.scala
src/test/scala/loamstream/util/ObservablesTest.scala

- Job-polling "successes" where no data is returned should no longer crash LS.
- The .tsv index files are written in more cases.  In particular, if LS crashes during pipeline execution, the .tsvs will be written with as much information as is readily available, notably jobs' directories under `.loamstream/jobs/data`.
- Shorter stack traces in some situations (uses less stack, and makes logs easier to read).
- Don't pass `-UF` to `bacct` now that EBI has upgraded their LSF cluster to 10.x.
Unit and integration tests pass.

Quality-Of-Life Improvements Based on Issues Discovered at EBI 

---

src/main/scala/loamstream/apps/AppWiring.scala
src/main/scala/loamstream/drm/AccountingClient.scala
src/main/scala/loamstream/drm/AccountingCommandInvoker.scala
src/main/scala/loamstream/drm/DrmChunkRunner.scala
src/main/scala/loamstream/drm/lsf/BacctAccountingClient.scala
src/main/scala/loamstream/drm/uger/QacctAccountingClient.scala
src/main/scala/loamstream/util/Futures.scala
src/main/scala/loamstream/util/Loops.scala
src/main/scala/loamstream/util/RetryingCommandInvoker.scala
src/test/scala/loamstream/drm/DrmChunkRunnerTest.scala
src/test/scala/loamstream/drm/MockAccountingClient.scala
src/test/scala/loamstream/drm/lsf/BacctAccountingClientTest.scala
src/test/scala/loamstream/drm/uger/MockQacctAccountingClient.scala
src/test/scala/loamstream/drm/uger/QacctAccountingClientTest.scala
src/test/scala/loamstream/util/LoopsTest.scala

- Wait for `{b,q}acct` retries asynchronously, instead of using `Thread.sleep()`
- Add `Loops.retryUntilSuccessWithBackoffAsync()`
Unit and integration tests pass.

Retry Accounting Clients Asynchronously

---

src/main/scala/loamstream/drm/DrmChunkRunner.scala
src/main/scala/loamstream/loam/intake/ColumnExpr.scala
src/test/scala/loamstream/drm/DrmChunkRunnerTest.scala

Running accounting clients (the things that ultimately invoke `qacct` et al) for every job is slow, and batching up jobs to invoke `qacct` on the whole batch has undesirable side effects without a more major refactoring.  What's more, the data obtained from qacct is very rarely useful unless a job fails.
This branch changes `DrmChunkRunner` to only invoke `AccountingClient`s for finished, non-successful jobs.

Invoke AccountingClients only for jobs that finish unsuccessfully

---

src/main/scala/loamstream/apps/Main.scala
src/test/scala/loamstream/apps/MainTest.scala

Make a stronger guarantee (in the face of `Error`s, especially `OutOfMemoryError`, all bets are off) that LS shuts down as gracefully as possible if any thread encounters an uncaught, fatal Exception.  This is motivated by a run where an OOM Error caused several worker threads - but not the main one - to die, leading to LS limping along in a state that would never finish or do useful work.

Make sure default uncaught exception handler shuts down Loamstream

---

src/main/scala/loamstream/googlecloud/GcsCloudStorageClient.scala
src/main/scala/loamstream/util/Base64.scala
src/main/scala/loamstream/util/Hash.scala
src/test/scala/loamstream/util/Base64Test.scala

Don't use any classes from `javax.xml.bind`, particularly `DatatypeConverter`, as this package is not bundled with the JRE post-Java-8.

Don't use classes from javax.xml.bind

---

src/main/scala/loamstream/loam/intake/flip/ReferenceFileHandle.scala
src/main/scala/loamstream/loam/intake/flip/ReferenceFiles.scala
src/test/scala/loamstream/loam/intake/flip/ReferenceFileHandleTest.scala

- Cache reference files in memory, resulting in a speedup of a few hundred times when processing big files with the intake DSL.
- The new code makes the same assumptions as the old code, and Marcin's Perl scripts: that the reference files are big sequences of 1-byte chars where positions in the file correspond to positions in the reference genome.

Cache fasta reference files in memory

---

src/main/scala/loamstream/compiler/LoamFile.scala
src/main/scala/loamstream/loam/intake/aggregator/AggregatorCommands.scala
src/main/scala/loamstream/loam/intake/aggregator/ColumnDefs.scala
src/main/scala/loamstream/loam/intake/aggregator/Metadata.scala
src/main/scala/loamstream/loam/intake/aggregator/SourceColumns.scala
src/main/scala/loamstream/loam/intake/rowDefs.scala
src/main/scala/loamstream/loam/intake/testing/UkbbDietaryGwas.scala
src/test/scala/loamstream/loam/intake/aggregator/MetadataTest.scala
src/test/scala/loamstream/loam/intake/examples/ReadMe.scala
src/test/scala/loamstream/util/Base64Test.scala

- Parameterize on column mappings instead of hard-coding when invoking `dig-aggregator-intake`.
- Wrap strings in quotes if they contain whitespace when generating Aggregator config files.
- Don't always add `--skip-validation` when invoking `dig-aggregator-intake`.
- Minor improvements to Loam examples.

Fixes for problems encountered during EBI data upload

---

src/main/scala/loamstream/model/execute/RxExecuter.scala
src/main/scala/loamstream/util/Observables.scala

This brings moderate readability and performance improvements.

Cleanups to RxExecuter; make it tuple-oriented instead of map-oriented

---

src/main/scala/loamstream/drm/DrmChunkRunner.scala
src/main/scala/loamstream/drm/DrmTaskArray.scala
src/main/scala/loamstream/loam/intake/ColumnExpr.scala
src/main/scala/loamstream/loam/intake/aggregator/AggregatorCommands.scala
src/main/scala/loamstream/loam/intake/aggregator/ColumnDefs.scala
src/test/scala/loamstream/loam/intake/ColumnExprTest.scala
src/test/scala/loamstream/loam/intake/aggregator/ColumnDefsTest.scala

Some things that came out of Ryan's last round of data-upload work:
- Allow passing a log file name to `AggregatorCommands.upload()` to make it easier to see output from `dig-aggregator-intake` while upload jobs are in-progress.  (Uger makes this inconvenient otherwise.)
- Add some more syntactic sugar to `aggregator.ColumnDefs`.
- Log locations of DRM shell scripts as they're copied to jobs' dirs at job-submission-time.

Intake DSL Improvements

---

src/main/scala/loamstream/loam/intake/aggregator/Metadata.scala
src/main/scala/loamstream/loam/intake/testing/UkbbDietaryGwas.scala
src/test/scala/loamstream/loam/intake/aggregator/MetadataTest.scala
src/test/scala/loamstream/loam/intake/examples/ReadMe.scala

To support recent Aggregator changes, make both cases/controls and subjects optional in Aggregator conf files.

Optional cases, controls, and subjects

---

src/main/scala/loamstream/db/slick/CommandDaoOps.scala
src/main/scala/loamstream/db/slick/ExecutionDaoOps.scala
src/main/scala/loamstream/model/execute/DbBackedExecutionRecorder.scala
src/main/scala/loamstream/model/execute/DbBackedJobFilter.scala
src/main/scala/loamstream/model/execute/RxExecuter.scala
src/main/scala/loamstream/model/jobs/Execution.scala
src/test/scala/loamstream/ExecutionResumptionEndToEndTest.scala
src/test/scala/loamstream/model/execute/DbBackedExecutionRecorderTest.scala
src/test/scala/loamstream/model/jobs/ExecutionTest.scala

A previous PR added the `Runs` table to the DB, and made LS delete info about the oldest `Run` on startup.  This has been successful at keeping the size of the DB in check, but made it possible for info about jobs to "age out" of the DB.  This happened because info about skipped jobs wasn't recorded, so running the same pipeline multiple times would result in a normal run of all jobs the first time, all jobs being skipped the next N times, and then all jobs being re-run once info from the first, successful run "aged out" of the DB.
This PR makes LS record info about skipped jobs.  Info still "ages out" of the DB, but this no longer results in info about existing job outputs being deleted, leading to job re-runs.

Record Skipped Job Executions to Avoid Spurious Re-Runs

---

src/main/scala/loamstream/compiler/LoamPredef.scala
src/main/scala/loamstream/conf/SingularityConfig.scala
src/main/scala/loamstream/drm/ContainerParams.scala
src/main/scala/loamstream/drm/DrmJobWrapper.scala
src/main/scala/loamstream/googlecloud/CloudSdkDataProcWrapper.scala
src/main/scala/loamstream/googlecloud/ClusterConfig.scala
src/main/scala/loamstream/googlecloud/GoogleCloudConfig.scala
src/main/scala/loamstream/googlecloud/HailCtlDataProcClient.scala
src/main/scala/loamstream/googlecloud/HailLoamSyntax.scala
src/test/resources/loamstream-test.conf
src/test/scala/loamstream/UgerConfigIsPropagatedToJobsTest.scala
src/test/scala/loamstream/compiler/LoamPredefTest.scala
src/test/scala/loamstream/conf/SingularityConfigTest.scala
src/test/scala/loamstream/db/slick/SlickLoamDaoTest.scala
src/test/scala/loamstream/drm/DrmJobWrapperTest.scala
src/test/scala/loamstream/drm/ScriptBuilderTest.scala
src/test/scala/loamstream/drm/lsf/BsubJobSubmitterTest.scala
src/test/scala/loamstream/drm/uger/QsubTest.scala
src/test/scala/loamstream/googlecloud/CloudSdkDataProcWrapperTest.scala
src/test/scala/loamstream/googlecloud/GoogleCloudChunkRunnerTest.scala
src/test/scala/loamstream/googlecloud/GoogleCloudConfigTest.scala
src/test/scala/loamstream/googlecloud/HailCtlDataProcClientTest.scala
src/test/scala/loamstream/googlecloud/HailSupportTest.scala
src/test/scala/loamstream/model/execute/FileSystemExecutionRecorderTest.scala

- Use `--region` when invoking `hailctl` (thanks @rmkoesterer ).
- Allow specifying extra params for Singularity via `loamstream.execution.singularity` key in `loamstream.conf`.

Add needed Hailctl and Singularity params

---

src/main/scala/loamstream/loam/intake/VariantRowExpr.scala
src/main/scala/loamstream/loam/intake/rows.scala

- Actually use inferred column definitions in VariantRowExpr 
- Treat pvalues as doubles and not strings in PValueVariantRow when making JSON

Fix variant column inference and data type of uploaded pvalues

---

src/main/scala/loamstream/drm/DrmChunkRunner.scala
src/main/scala/loamstream/drm/DrmJobWrapper.scala
src/main/scala/loamstream/drm/RateLimitedPoller.scala
src/main/scala/loamstream/loam/intake/dga/Json.scala
src/test/scala/loamstream/drm/DrmJobWrapperTest.scala
src/test/scala/loamstream/drm/RateLimitedPollerTest.scala
src/test/scala/loamstream/drm/ScriptBuilderTest.scala
src/test/scala/loamstream/googlecloud/GoogleCloudChunkRunnerTest.scala

Merge some outstanding BCH-Slurm-related work with the code that worked in the end (to the best of my knowledge).  Changes:
- Don't read from `stats` files when determining exit status for jobs, only use `exitcode` files.  
- Get tests passing.

Address BCH Slurm Woes

---

src/main/scala/loamstream/googlecloud/CloudSdkDataProcWrapper.scala

The Google Cloud SDK gcloud delete command was hanging up because it asked for user input (Y/N) and waited for it indefinitely. Adding the --quiet flag led to successful google cloud cluster deletion.

Rk fix gc cluster deletion hang
